sudo: required
services:
  - docker
before_install:
  - docker build -t hunghoang/docker-react -f Dockerfile.dev .
script:
  - docker run hunghoang/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "us-west-2"
  app: "docker-react"
  evn: "DockerReact-env"
  bucket_name: "elasticbeanstalk-us-west-2-531723182294"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"